try:
    print (4 / 2)
except NameError:
    print("NameError!")
else:
    print("No exceptions raised by the try block!")

#output
#2.0
#No exceptions raised by the try block!
